### ISSUE TITLE
配置文件中的table_name字段没有实际使用

### ISSUE THREAD

**Issue by Meepoljdx** [gin-admin/gin-admin-cli#12]
**当前使用版本**
feat/v10

**Bug描述**
使用-c参数指定配置文件生成业务模型，table_name参数指定的表名不生效，应该是template中没有使用这个创建表名
我在scheme.go.tpl中添加的如下代码重新编译的，作者大大可以考虑修复下这个问题
```go
{{ if .TableName }}
// Use `{{ .TableName }}` as TableName
func (a *{{$name}}) TableName() string {
	return "{{ .TableName }}"
}
{{ end }}
```

**Comment by LyricTian** [comment]
Fixed: <https://github.com/gin-admin/gin-admin-cli/blob/main/tpls/default/schema.go.tpl#L21-L25>
