### ISSUE TITLE
window 生成寻找不到模板文件报错

### ISSUE THREAD

**Issue by sigam-Zq** [gin-admin/gin-admin-cli#16]
win10 64位

gin-admin-cli 版本如下

gin-admin-cli version v10.3.1

错误报错如下

gin-admin-cli gen -d . -m Comm --structs Param --structs-comment 'Param 系统参数' --structs-router-prefix=true
2024-01-19T09:40:32.530+0800    ERROR   [GEN]   Failed to parse tpl, err: open tpls\default\schema.go.tpl: file does not exist, #struct Param, #tpl default\schema.go.tpl
github.com/gin-admin/gin-admin-cli/v10/internal/actions.(*GenerateAction).generate
        D:/desktop/gitDemo/go/gin-admin-cli/internal/actions/generate.go:216
github.com/gin-admin/gin-admin-cli/v10/internal/actions.(*GenerateAction).run
        D:/desktop/gitDemo/go/gin-admin-cli/internal/actions/generate.go:89
github.com/gin-admin/gin-admin-cli/v10/internal/actions.(*GenerateAction).RunWithStruct
        D:/desktop/gitDemo/go/gin-admin-cli/internal/actions/generate.go:84
github.com/gin-admin/gin-admin-cli/v10/cmd.Generate.func1
        D:/desktop/gitDemo/go/gin-admin-cli/cmd/generate.go:104
github.com/urfave/cli/v2.(*Command).Run
        C:/Users/zq102/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:274
github.com/urfave/cli/v2.(*Command).Run
        C:/Users/zq102/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:267
github.com/urfave/cli/v2.(*App).RunContext
        C:/Users/zq102/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:332
github.com/urfave/cli/v2.(*App).Run
        C:/Users/zq102/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:309
main.main
        D:/desktop/gitDemo/go/gin-admin-cli/main.go:47
runtime.main
        D:/Environment/go1.21/go1.21.0.windows-amd64/go/src/runtime/proc.go:267
panic: open tpls\default\schema.go.tpl: file does not exist

尝试重新编译 也不通过

**Comment by LyricTian** [comment]
可能跟 go embed 文件系统有关系，尝试更新一下试试：<https://github.com/gin-admin/gin-admin-cli/releases/tag/v10.3.3>
